# Generated by Django 5.1.7 on 2025-03-11 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('pre', 'Encuesta I (Antes de la experiencia)'), ('post', 'Encuesta II (Después de la experiencia)')], max_length=10)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('pre', 'Encuesta I (Antes de la experiencia)'), ('post', 'Encuesta II (Después de la experiencia)')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula de identidad debe contener exactamente 10 números.')])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-záéíóúÁÉÍÓÚÑñ' -]+$", 'El nombre debe contener solo letras, apóstrofes o guiones.')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-záéíóúÁÉÍÓÚÑñ' -]+$", 'El nombre debe contener solo letras, apóstrofes o guiones.')])),
                ('cycle', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
                ('itinerary', models.CharField(choices=[('software', 'Ingeniería de Software'), ('inteligentes', 'Sistemas Inteligentes'), ('aplicada', 'Computación Aplicada')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tic_home.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tic_home.survey')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tic_home.user'),
        ),
    ]
