# Generated by Django 5.1.7 on 2025-03-12 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_home', '0002_remove_question_survey_type_question_survey_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Estudiante',
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='survey_type',
            field=models.CharField(choices=[('pre', 'Encuesta I (Antes de la experiencia)'), ('post', 'Encuesta II (Después de la experiencia)')], default='pre', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
