# Generated by Django 5.1.7 on 2025-04-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_home', '0003_rename_user_estudiante_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_experiencia',
            field=models.CharField(blank=True, choices=[('rv_no_inmersiva', 'RV No Inmersiva'), ('semi_inmersiva', 'Semi Inmersiva'), ('inmersiva', 'Inmersiva')], max_length=20, null=True),
        ),
    ]
