# Generated by Django 5.1.7 on 2025-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_home', '0004_estudiante_tipo_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_experiencia',
            field=models.CharField(blank=True, choices=[('inmersiva', 'Realidad Virtual Inmersiva'), ('no_inmersiva', 'Realidad Virtual No Inmersiva')], max_length=20, null=True),
        ),
    ]
