# Generated by Django 5.1.7 on 2025-06-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_home', '0005_alter_estudiante_tipo_experiencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'survey_type', 'section', 'order']},
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('inmersiva', 'Realidad Virtual Inmersiva'), ('no_inmersiva', 'Realidad Virtual No Inmersiva')], default='inmersiva', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('cerrada', 'Cerrada'), ('abierta', 'Abierta')], default='cerrada', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('utilidad', 'Utilidad Percibida'), ('facilidad', 'Facilidad de Uso Percibida'), ('actitud', 'Actitud hacia el Uso'), ('intencion', 'Intención de Uso')], default='utilidad', max_length=20),
        ),
    ]
